### ISSUE TITLE
Column name not escaped if column name is a reserved SQL word

### ISSUE THREAD

**Issue by c-nichols** [aykut/django-bulk-update#17]
For instance, I have a column named `default` -- when attempting to update I get this error:
```
django.db.utils.ProgrammingError: syntax error at or near "default"
LINE 1: UPDATE myapp_mymodel SET default = CAST(CASE id WHEN...
```

**Comment by c-nichols** [comment]
In contrast, django generates SQL that looks like this:
```
UPDATE "myapp_mymodel" SET "default" = True, "other_field" = something, ...
```

**Comment by daleobrien** [comment]
I've put in a pull request (#19) which should fix your problem.

**Comment by c-nichols** [comment]
Sorry for the delay -- much thanks for the pull request!  Working like a charm.
