### ISSUE TITLE
helper.bulk_update seems to fail when only one pk

### ISSUE THREAD

**Issue by serguitus** [aykut/django-bulk-update#31]
At ```./helper.pyL#63``` paramaters contains a tuple of ids for the WHERE condition (```WHERE pk in (val1, val2)```)
when there is only one item to update then the resulting sql ends in ``` WHERE pk in (val1,)``` so I get 
```(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1")```
I know that if I'm not going to update only one object, then I should not use bulk_update but, shouldn't this be capable of handling also a list of only 1 item? or at list handle the error :-)
A code like this on ```./helper.pyL#57``` fixed the issue for me
```python
   if len(pks) > 1:
                paramaters.extend([tuple(pks)])
                sql = 'UPDATE {dbtable} SET {values} WHERE {pkcolumn} in %s'\
                    .format(dbtable=dbtable, values=values, pkcolumn=pkcolumn)
            else:
                paramaters.extend(pks)
                sql = 'UPDATE {dbtable} SET {values} WHERE {pkcolumn} in (%s)'\
                    .format(dbtable=dbtable, values=values, pkcolumn=pkcolumn) 
```
I don't know if you like the idea. If you do, then I could do a PR for you
Thanks for this nice tool

**Comment by aykut** [comment]
Hi,
You are certainly right that it must also handle lists with one item. It is clearly a bug.

I'll investigate and make a patch as soon as possible.

Thanks.

**Comment by aykut** [comment]
Hi,
It seems ok with mysql as I just created a test case for this situation. Are you still having the problem.

Thanks.

**Comment by serguitus** [comment]
I will try and get back to you
