### ISSUE TITLE
update_fields for foreign key

### ISSUE THREAD

**Issue by ruscoder** [aykut/django-bulk-update#33]
Hello. I am found a problem with update_fields with foreign keys. In Django update_fields works as `instance.save(update_fields=['foreignkey'])`
In bulk_update its works only in one case: ``instance.save(update_fields=['foreignkey_id'])``

**Comment by aykut** [comment]
I have fixed it here https://github.com/aykut/django-bulk-update/commit/1114cf04d999e346c239f083d28925b1ebe4a40d

Thanks for pointing out.
