### ISSUE TITLE
Bulk_update helper gives an error if len(list) is smaller than the batch_size

### ISSUE THREAD

**Issue by ketanbhatt** [aykut/django-bulk-update#44]
bulk_update helper gives `IndexError: list index out of range` when `batch_size` is larger than `len(list)`. This shouldn't happen and `bulk_update` should gracefully handle it.

The fix would be easy, can i send a PR?

**Comment by aykut** [comment]
Of course you can, and please add tests that covers the case.

Thanks.

**Comment by ketanbhatt** [comment]
Ok this was fixed in https://github.com/aykut/django-bulk-update/pull/36 :disappointed: 
I was just on an old version.
