### ISSUE TITLE
Specifying `batch_size` on bulk_update would only process the first batch

### ISSUE THREAD

**Issue by rabogaa** [aykut/django-bulk-update#45]
The remaining data is not processed when specifying `batch_size` when using `bulk_update.helper.bulk_update` function. This is because `lenpks` is returned after processing the first batch. Ideally, `lenpks` should be returned after all data are processed right? 
 
```connection.cursor().execute(sql, parameters)```
```return lenpks```

**Comment by aykut** [comment]
Yes, you are right. It is fixed with v1.1.10, please upgrade your package.
Thanks.
