### ISSUE TITLE
Many to many field

### ISSUE THREAD

**Issue by BennievanderWel** [aykut/django-bulk-update#70]
Hi there,

Bulk updating a many-to-many field gives me the following error:

These fields are not present in current meta: my_many_to_many_field

I see the package only checks the _meta of the model and validates if the fields to be updated are present in there. However, many_to_many field references are stored in _meta.many_to_many. Any suggestions how I should approach this? Is this a bug or as designed? I'm not extremely experienced with many-to-many fields.

Thanks in advance!

Bennie

**Comment by arnau126** [comment]
It's as designed. We don't support updating fields which are not materialized in the table that we want to update.

A many-to-many field is not stored in any of the two tables of the relation, but in a third one just created to store this relation.

To update a many-to-many field we should delete and insert rows from this third table.

**Comment by BennievanderWel** [comment]
OK, thanks for the reply. Any suggestions on how one might do this?
